version: 2
jobs:
  staff-sync:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker run --rm \
              -e CONNPASS_USERNAME \
              -e CONNPASS_PASSWORD \
              -e SERVICE_ACCOUNT_INFO_AS_STR \
              pyconjp/mogirin-db-synchronizer:0.0.1 \
              224112 \
              ${SPREADSHEET_ID}

workflows:
  version: 2
  staff-sync-wf:
    jobs:
      - staff-sync:
          filters:
            branches:
              only: main
