version: 2
jobs:
  staff-sync:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "Testing"
      - run: docker run --rm pyconjp/mogirin-db-synchronizer:0.0.1 224112

workflows:
  version: 2
  staff-sync-wf:
    jobs:
      - staff-sync:
          filters:
            branches:
              only: main
